before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev libqt5xmlpatterns5-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
 - cd sepiaGen
 - qmake
 - make
 - cd plugins/CppQt-RSB
 - qmake
 - make
